### ISSUE TITLE
Improve how we pass configuration information to the plugin

### ISSUE THREAD

**Issue by AdamBJ** [umple/umple.gradle#8]
We're currently allowing users to override the default plugin configuration values by adding an extension to the project (`project.ext.('outputPath', 'my/path')`). We need to research a way to do this in a less hacky way, or agree that we're going to do it in the dumb way.

Once we make this decision, https://github.com/umple/umple.gradle/issues/7 needs to be dealt with.

**Comment by AdamBJ** [comment]
@Nava2 I figured out how to add extra properties to source sets: https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties.

I've got it working in my test project. So now instead of associating the configuration information with the project itself, the information's associated with the `generatedSource` source set. We're still using the same `ext` functionality, but at least we're not polluting the project anymore.

**Comment by Nava2** [comment]
I think this looks like a great way to do this (sorry that I didn't see this before). 

As long as the _users_ aren't writing `project.ext.foo = bar` I think it's great. Ergonomics are important to _users_ not plugin developers in this context.

**Comment by AdamBJ** [comment]
Alright, I'll try to get to this today or tomorrow. The plugin readme will need to be updated as part of this fix, too. Instead of having to set the `ext` field on the `project`, users will need to create the `generatedSource` source set and set the `ext` fields there.
