### ISSUE TITLE
Add integration tests to the plugin

### ISSUE THREAD

**Issue by AdamBJ** [umple/umple.gradle#9]
The plugin currently has no unit or integration tests. Before we go too far with the [Umple build conversion from Ant](https://github.com/umple/umple/issues/751#issuecomment-282145135), we should add JUnit integration and unit tests to the plugin to make sure we don't break anything as we develop the Gradle build. 

The test should cover applying the plugin to a project, generating files using the plugin, compiling files after generation... etc.

**Comment by AdamBJ** [comment]
@Nava2 I've got a PR 95% ready to go to address this issue. The main thing blocking me is not being able to update the plugin in the Gradle plugin portal. Right now my build files are pointing to a local plugin jar, and if I submit a PR now you guys are going to need to change to path to point to where ever the local jar is on your system... much easier to just get everything from the plugin portal. I'm going to email Tim about getting tomorrow once he's back.

While we wait, I'll push my changes to a branch today or tomorrow so you can have a look. You won't be able to run the code on your machine very easily because of the plugin jar issue I just mentioned, but you'll be able to get a feel for what I've done.

**Comment by vahdat-ab** [comment]
@AdamBJ  check your email. I sent the key to your email.

**Comment by Nava2** [comment]
@AdamBJ we should investigate how to do testing w/o the portal. This may involve a hard-coded path, but we would not want to update the portal with unreviewed code.

**Comment by AdamBJ** [comment]
@Nava2  To use a locally built copy of the plugin jar, have a look at the `buildscript` closure in the `build.gradle` file of `TestProject`. All you need to do is uncomment line 6 and 15 and comment out lines 7-9 and 14. Of course, you're also going to need to change `C:/Users/i_am_/workspace/umple.gradle/build/libs` to wherever you're storing the locally build plugin jar on your machine.

Doing that will force `TestProject` to use a local copy of the jar, but you can reuse the `buildscript` closure from `TestProject` in any Gradle project you want.

If you're talking about using a local jar in the TravisCI testing, then it's bit more complex. We might have to include a locally built jar in the Github repo? Hopefully there's a more elegant solution than that.

**Comment by Nava2** [comment]
That's not quite good enough. It'll probably require some bootstrapping, but we need to test it without manual specification.
